'use strict';

angular.module('myApp.references', ['ngRoute'])
.controller('ReferencesCtrl', [ '$rootScope', '$scope', '$mdToast', '$window', function($rootScope, $scope, $mdToast, $window) {
    $rootScope.activeLink = 'references';

    $scope.references = [
        'ABB Robots, Inc.',
        'Ace Systems Division',
        'Airway, Inc.',
        'Alliance Manufactured Products',
        'AMC',
        'Asked Automation',
        'Bertrand Faure',
        'Burton Industries',
        'CD Product, Inc.',
        'Citation Tool, Inc.',
        'Comau North America',
        'Combine Tool & Die Company',
        'Conveyormatic',
        'Custom Manufacturing',
        'Daniel Electric',
        'D.C.T. Automation',
        'Dearborn Gage',
        'Double Nickel',
        'Durr Automation',
        'Fata Aluminum, Inc.',
        'FEC Automation',
        'Ferguson Company',
        'Frimo, Inc.',
        'Gehring Corporation',
        'General Inspection',
        'Gonzalez Pro duction Systems',
        'Hansford Automation Systems',
        'Hegenscheidt Corporation',
        'Hirotech',
        'Hi-Tech Systems, Inc.',
        'Hovair products',
        'Hydro-Logic, Inc.',
        'Hydro-Tech',
        'Ingersoll-Rand Company',
        'J & D Tool & Gage',
        'Key Welders',
        'K J Law',
        'Kuka Welding & Robotics',
        'Lamb Technicon',
        'Link Engineering',
        'Manufacturing Control Systems',
        'Oakley Sub Assembly',
        'Outbound Technologies',
        'Paslin Corporation',
        'Peck Automation',
        'Pico Resources',
        'Progressive Tool & Industries',
        'Ransohoff, Inc.',
        'Robotic Production Technology',
        'Sanyo Machine',
        'Spen-Tech Machine',
        'Steel Masters',
        'Steph-Fran',
        'Summit Engineering',
        'Tesco Engineering',
        'Thermal Tool Alpha',
        'Thielenhaus Manufacturing',
        'Three M Tool',
        'Ti-Coating',
        'Tri Tech Controls',
        'Utilase Systems, Inc.',
        'VSI Automation Assembly',
        'Wamcor, Inc',
        'Wilson Automation',
        'Windsor Industrial Service',
        'Woodbridge Corporation',
        'Wright & Company',
        'X-Bar Automation'
    ]
}]);
